/*
 * BBS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// BoardListGet -
func (s *DefaultApiService) BoardListGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update BoardListGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, BoardListResponse{}) or use other options such as http.Ok ...
	//return Response(200, BoardListResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("BoardListGet method not implemented")
}

// ServerIdBoardIdThreadListGet -
func (s *DefaultApiService) ServerIdBoardIdThreadListGet(ctx context.Context, serverId string, boardId string) (ImplResponse, error) {
	// TODO - update ServerIdBoardIdThreadListGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ThreadListResponse{}) or use other options such as http.Ok ...
	//return Response(200, ThreadListResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServerIdBoardIdThreadListGet method not implemented")
}

// ServerIdBoardIdThreadThreadIdGet -
func (s *DefaultApiService) ServerIdBoardIdThreadThreadIdGet(ctx context.Context, serverId string, boardId string, threadId string) (ImplResponse, error) {
	// TODO - update ServerIdBoardIdThreadThreadIdGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, ThreadResponse{}) or use other options such as http.Ok ...
	//return Response(200, ThreadResponse{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ServerIdBoardIdThreadThreadIdGet method not implemented")
}
