/*
 * BBS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BoardListResponseBoardList struct {
	Name string `json:"name,omitempty"`

	Server string `json:"server,omitempty"`

	BoardId string `json:"board_id,omitempty"`
}
