/*
 * BBS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ThreadResponseMeta struct {
	Number int32 `json:"number,omitempty"`

	Name string `json:"name,omitempty"`

	PostedAt time.Time `json:"posted_at,omitempty"`

	UserId string `json:"user_id,omitempty"`

	Comment string `json:"comment,omitempty"`
}
