/*
 * BBS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ThreadListResponseThreadList struct {
	Id string `json:"id"`

	Name string `json:"name"`
}

// AssertThreadListResponseThreadListRequired checks if the required fields are not zero-ed
func AssertThreadListResponseThreadListRequired(obj ThreadListResponseThreadList) error {
	elements := map[string]interface{}{
		"id":   obj.Id,
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseThreadListResponseThreadListRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ThreadListResponseThreadList (e.g. [][]ThreadListResponseThreadList), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseThreadListResponseThreadListRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aThreadListResponseThreadList, ok := obj.(ThreadListResponseThreadList)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertThreadListResponseThreadListRequired(aThreadListResponseThreadList)
	})
}
