/*
 * BBS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BoardListResponse struct {
	LastUpdated string `json:"last_updated,omitempty"`

	BoardList []BoardListResponseBoardList `json:"board_list,omitempty"`
}
