/*
 * BBS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type CommentMeta struct {
	Number int32 `json:"number"`

	UserName string `json:"user_name"`

	UserId string `json:"user_id"`

	PostedAt time.Time `json:"posted_at"`
}
