/*
 * BBS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ThreadListResponseThreadList struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}
