/*
 * BBS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Board struct {
	Name string `json:"name"`

	ServerId string `json:"server_id"`

	BoardId string `json:"board_id"`
}
