/*
 * BBS API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ThreadListResponse struct {
	ThreadList []ThreadListResponseThreadList `json:"thread_list,omitempty"`
}
